spring:
  datasource:
    url: jdbc:h2:mem:memdb
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
    show-sql: true
spring.main.allow-circular-references: true
springdoc:
  api-docs:
    path=/api-docs: