spring:
  data:
    mongodb:
      database: books
  mongodb.embedded.version: 3.5.5
  main.allow-circular-references: true
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.slepukhin.mongock.changelog

